### ISSUE TITLE
TopBar Plugin - Unable to display dropdown

### ISSUE THREAD

**Issue by laymonk** [ibericode/mc4wp-snippets#11]
Hi,

I am trying to add extra fields to the Top Bar plugin.  The input fileds work fine, but I just cannot get a dropdown field to display.  

I get a display like the following image:
![2018-04-29_17h53_09](https://user-images.githubusercontent.com/1984029/39408969-631b45e4-4bd6-11e8-84ea-4bca6b5f8250.png)

Does it mean that the TopBar plugin cannot handle select fields ?

Thanks

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-top-bar

When you post about the issue on the forum please also share a link to a page where we can see and test the issue for you.

Thank you!
