### ISSUE TITLE
Hidde elements are not synced properly to MC

### ISSUE THREAD

**Issue by tonybahama** [ibericode/mc4wp-snippets#12]
Hi!

There is a bug in the MC4WP woocommerce premoum plugin.

**You do not set visibility for the products.**

This means MC shows old drafted, and out of stock items as well.

Please create a filter that that does the following.

**Default: visibility --> "visible"**

**Set it to "hidden":**
- If the product is either draft either private status, set it to hidden! OR
- Also set it to hidden, if the catalog visibility is set to hidden

Or please put this this feature ASAP in a release, as it now MC shows a bunch of outdated draft items to customers they cannot purhase.

Thanks!
Leventre

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
