### ISSUE TITLE
Is there a way to add a help button (pop up window) inthe form?

### ISSUE THREAD

**Issue by BenitaThes** [ibericode/mc4wp-snippets#14]
Hi,

I would need to insert a help button or similar to one specific field in my form explaining where to find the information a person needs in order to fill correct information in the field. Is there a way to do it with Mailchimp for Wordpress?

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
