### ISSUE TITLE
Existing Subscriber Tag add and keep his exiting tag if have in mailchimp

### ISSUE THREAD

**Issue by HemantHapani** [ibericode/mc4wp-snippets#15]
Hello,

I have installed plugin and set xyz tag for new subscriber and its working fine.

But for existing user its not added xyz tag.

Suppose test@gmail.com is already existing user in mailchimp list and has tag 'ABC'.

When again he do subscribe then 'ABC' his existing tag and  new tag 'XYZ' tag is need to add.

So, How I can do that?

Thanks
Hemant

**Comment by MarvinChacon** [comment]
I have the same issue

**Comment by arnelap** [comment]
Using tags at this time it's not possible to update/add tags. I recommend using Interest groups in the place of tags, interest groups are much better supported in the MailChimp API. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
