### ISSUE TITLE
Issue with OptimizeMember fields in User Sync snippet.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mc4wp-snippets#2]
it works when the optimizemember field is single selection
if the optimizemember field is multiple selection (drop down) it only syncs the first selection
if the optimizemember field is multiple selection (checkbox) it doesn't sync anything

See https://github.com/ibericode/mc4wp-snippets/blob/master/add-ons/user-sync/optimizemember-custom-fields.php

**Comment by arnelap** [comment]
https://secure.helpscout.net/conversation/129133982/3921/?folderId=253123
