### ISSUE TITLE
User Sync, remove from grouping?

### ISSUE THREAD

**Issue by adaptifyDesigns** [ibericode/mc4wp-snippets#4]
Love the helpful snippet on [adding users to specific groupings](https://github.com/ibericode/mc4wp-snippets/blob/master/add-ons/user-sync/exclude-roles.php).

One problem is that if a MC subscriber is already in a grouping, how can I take them out of it based on a WP role change?

To use the same example as in the snippet, if a user has role Subscriber and therefore has already been added to the "Membership Status: Member" grouping, but then is downgraded to role Customer, they will be given the "Membership Status: Paused", but will retain their previous "Membership Status: Member", thus being in two groupings. I'd like the users to be in _either_ 'Member' _or_ 'Paused' but not both. 

Is there a way to remove them from one or the other via the `mailchimp_sync_user_data` filter?

Thanks!

**Comment by arnelap** [comment]
https://github.com/ibericode/mc4wp-snippets/blob/master/add-ons/user-sync/groupings.php

but instead of = true you set it to = false to remove them.
