### ISSUE TITLE
Custom Integration & Custom Form Validation

### ISSUE THREAD

**Issue by ChrisSargent** [ibericode/mc4wp-snippets#6]
Hi Danny,

Is it possible to hook in to the mc4wp_form_errors filter from a custom form?

I have a custom form that I'm running some custom validation on and I'd like to prevent subscribing the user until that validation has passed.

Thanks,

Chris

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests and are usually not able to respond to support requests posted as Git Issue in a timely manner.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-for-wp
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
