### ISSUE TITLE
Add custom classes to form element with mc4wp_form?

### ISSUE THREAD

**Issue by j-greig** [ibericode/mc4wp-snippets#7]
Is there a way to modify the shortcode to accept classes as an argument?

(My CSS framework doesn't work with IDs)

Thanks!

James

**Comment by dannyvankooten** [comment]
Hi James,

There's currently no way to pass additional CSS classes to the form HTML but there is a filter for that.

```php
add_filter( 'mc4wp_form_css_classes', function( $classes ) {
	$classes[] = 'my-class';
	return $classes;
});
```

That said, I can see how it makes sense to pass those from the shortcode or function call so I am going to leave this open to see if we can start supporting this. :)

**Comment by j-greig** [comment]
Thanks @dannyvankooten :) 

(And yes I found the filter, but it applies the same classes to every form, so not _quite_ what I need, have managed to hack a solution for now though).

**Comment by dannyvankooten** [comment]
Hi @j-greig,

We haven't yet released this but our GitHub master branch now allows passing an `element_class` attribuet to the shortcode or `mc4wp_show_form` function.

```
[mc4wp_form element_class="class-one class-two"]
```

```php
mc4wp_show_form( 500, array( 'element_class' => 'my-css-class' ) );
```

We're releasing this later this week! :)
