### ISSUE TITLE
How to trigger subscribe_from_woocommerce_checkout()

### ISSUE THREAD

**Issue by ralphioooo** [ibericode/mc4wp-snippets#8]
How would I fire subscribe_from_woocommerce_checkout() again from functions.php ? 

Also how do I access / trigger this function and pass some user data to it:
http://developer.mc4wp.com/reference/classes/mc4wp_api_v3/add_list_member/

**Comment by dannyvankooten** [comment]
Hi @ralphioooo,

This method is not meant to be called manually, it should be called by the plugin when you have configured the WooCommerce integration via the Integration settings page.

If you want to manually issue a subscribe call then I recommend using the `mc4wp_get_api()` function to retrieve an instance of the `MC4WP_API_v3`  class so that you can call the method you linked to, for example.

```php
$api = mc4wp_get_api();
$api->add_list_member( 'list-id', [ 'email_address' => 'ralph@email.com' ]);
```

**Comment by ralphioooo** [comment]
Thanks @dannyvankooten I tried the manual way but get the follow error:
PHP Fatal error:  Uncaught Error: Call to undefined method MC4WP_API::add_list_member() 

The object seems ok however: 
object(MC4WP_API)#10155 (6) { ["api_url":protected]=> string(35) "https://us12.api.mailchimp.com/2.0/" ["api_key":protected]=> string(37) "HAVEHIDDENTHIS-us12" ["error_message":protected]=> string(0) "" ["error_code":protected]=> int(0) ["connected":protected]=> NULL ["last_response":protected]=> NULL }

**Comment by dannyvankooten** [comment]
Hi @ralphioooo,

Oops. I'm sorry, I made a mistake in my previous code snippet. That function returns the older v2 API class where the new API v3 class is returned by calling `mc4wp_get_api_v3`.

The full example should have read.

```php
$api = mc4wp_get_api_v3();
$api->add_list_member( 'list-id', [ 'email_address' => 'ralph@email.com' ]);
```

**Comment by ralphioooo** [comment]
Thank you - all go :)

**Comment by ralphioooo** [comment]
Sorry one more question. What is the array structure for the batch version: http://developer.mc4wp.com/reference/classes/mc4wp_api_v3/add_list_members/#source-code

I tried passing an array... but did not work. Said it needed an object. When I sent an object it said it need to be an array.
