### ISSUE TITLE
User password and login credentials

### ISSUE THREAD

**Issue by yaarite** [ibericode/mc4wp-snippets#9]
Currently this code successfully ads a WordPress user from a mail chimp sign up but does not assign a password or send out an email with user credentials? User cannot access wordpress as a subscriber or customer until I manually assign a password to the account

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests and are  not able to respond to support requests posted as Git Issue in a timely manner. However, for UserSync we currently can't provide any support at all. Please see: https://wordpress.org/support/topic/sticky-if-you-need-support-for-mailchimp-user-sync-read-this-first/

You can still create a support ticket here: https://wordpress.org/support/plugin/mailchimp-sync/ maybe another user will respond. 

Thank you!
